version: "3"

services: 
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - mongo-data:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./dump:/dump

volumes: 
  mongo-data: