version: "3"

services: 
  mongodb:
    image: mongo
    restart: unless-stopped
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - mongo-data:/data/db
      - ./dump:/dump

  web: 
    build: .
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 22606:3000
    environment:
      - NODE_ENV=production

volumes: 
  mongo-data: