# This workflow will do a clean install of node dependencies, build the source code, and push the resulting image to the Azure Container Repository

name: Build and Deploy to TEST

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  workflow_dispatch:

jobs:

  login:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      -
        name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_URI }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      -
        uses: actions/checkout@v2
        with:
          ref: test
      - name: Build the new Docker image and uniquely tag
        run: docker build . --tag ${{ secrets.ACR_URI }}/data-dictionary_test:${{ github.sha }}
      - name: Push the new Docker image
        run: docker push ${{ secrets.ACR_URI }}/data-dictionary_test:${{ github.sha }}
      - name: Tag latest
        run: docker tag ${{ secrets.ACR_URI }}/data-dictionary_test:${{ github.sha }} ${{ secrets.ACR_URI }}/data-dictionary_test:latest
      - name: Push latest
        run: docker push ${{ secrets.ACR_URI }}/data-dictionary_test:latest
